# https://www.gitpod.io/docs/config-gitpod-file

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: notify

tasks:
  - name: Restore .env file
    command:
      if [ -f .env ]; then
        echo "Found .env in workspace"
      else
        if [ ! -n "${ENV}" ]; then
          echo "Setting example .env"
          cp .env.example .env
        else
          echo "Restoring .env from Gitpod"
          echo "${ENV}" | base64 -d | tee .env > /dev/null
        fi
      fi
  - name: Docker
    init: docker-compose pull
    command: docker-compose up

  - init: npm install
    command: |
      gp await-port 5432
      npm run setup
      npm run build
      npm run dev

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss